{application,dist,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{dist_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[dist,dist_app,dist_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
